let DATA; const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const agendaKey='cea2026_agenda_v2';
async function init(){DATA=await fetch('data/evento.json').then(r=>r.json());bindStatic();bindDeadlineNotice();renderInicio();renderProgram();renderAgenda();bindNav();tick();setInterval(tick,60000)}
function bindStatic(){const e=DATA.evento,r=DATA.recursos;$('#heroImg').src=r.hero;$('#summaryImg').src=r.resumenVisual;$('#objective').textContent=e.objetivo;$('#audience').textContent=e.dirigidoA;$('#address').textContent=e.direccion;['registerTop','registerMid','registerBottom','registerNotice','registerStrip'].forEach(id=>$('#'+id).href=e.registroUrl);['callTop','callBottom','callNotice'].forEach(id=>$('#'+id).href=r.convocatoriaPdf);$('#emailLink').href='mailto:'+e.contacto;$('#emailLink').textContent=e.contacto}

function bindDeadlineNotice(){const modal=$('#deadlineModal'),close=$('#deadlineClose');if(!modal||!close)return;const key='cea2026_deadline_notice_20260930';if(sessionStorage.getItem(key)==='closed')modal.classList.add('is-hidden');close.onclick=()=>{modal.classList.add('is-hidden');sessionStorage.setItem(key,'closed')};modal.addEventListener('click',e=>{if(e.target===modal){modal.classList.add('is-hidden');sessionStorage.setItem(key,'closed')}})}
function renderInicio(){$('#modalidades').innerHTML=DATA.modalidadesParticipacion.map((m,i)=>`<article class="mode"><span class="num">0${i+1}</span><h3>${esc(m.nombre)}</h3><p>${esc(m.descripcion)}</p><small>${esc(m.maxParticipantes)}</small></article>`).join('');$('#tematicas').innerHTML=DATA.tematicas.map(t=>`<div class="theme">${esc(t)}</div>`).join('');const central=(DATA.programaGeneral||[]).filter(x=>x.tipo==='Conferencia Magistral'||x.actividad.includes('Inauguración')||x.actividad.includes('Clausura'));const host=$('#centralMoments');if(host)host.innerHTML=central.map(x=>`<article class="moment"><span>${esc(x.fechaTexto)} · ${esc(x.horario)}</span><h3>${esc(x.actividad)}</h3>${x.ponente?`<p>${esc(x.ponente)}</p>`:''}</article>`).join('')}
function tick(){const end=new Date(DATA.evento.registroCierre),now=new Date(),d=end-now,el=$('#countdown');if(d<=0){el.textContent='Recepción cerrada';return}const days=Math.floor(d/86400000),hrs=Math.floor((d%86400000)/3600000);el.textContent=`${days} días · ${hrs} h restantes`}
function bindNav(){$$('#mainNav a').forEach(a=>a.addEventListener('click',()=>showView(a.dataset.view)));$('#menuBtn').onclick=()=>{const n=$('#mainNav');n.classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',n.classList.contains('open'))};window.addEventListener('hashchange',()=>showView(location.hash.slice(1)||'inicio'));showView(location.hash.slice(1)||'inicio')}
function showView(id){if(!['inicio','programa','agenda','constancias'].includes(id))id='inicio';$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('#mainNav a').forEach(a=>a.classList.toggle('active',a.dataset.view===id));$('#mainNav').classList.remove('open');window.scrollTo(0,0);if(id==='agenda')renderAgenda()}
function allItems(){const pg=(DATA.programaGeneral||[]).map(x=>({...x,kind:'programa',titulo:x.actividad,lugar:x.sede||'',modalidad:'Presencial'}));const tw=(DATA.talleres||[]).map(x=>({...x,kind:'taller',actividad:x.titulo,tipo:'Taller',modalidad:'Presencial'}));return [...pg,...tw]}
function renderProgram(){const rows=allItems();$('#programToolbar').hidden=false;buildFilters(rows);['globalSearch','filterDay','filterType'].forEach(id=>$('#'+id).addEventListener(id==='globalSearch'?'input':'change',()=>renderRows(rows)));$$('[data-program-tab]').forEach(b=>b.onclick=()=>{$$('[data-program-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#programMode').value=b.dataset.programTab;renderRows(rows)});renderRows(rows)}
function buildFilters(rows){fill('#filterType',uniq(rows.map(x=>x.tipo)));}
function fill(sel,arr){$(sel).insertAdjacentHTML('beforeend',arr.filter(Boolean).map(x=>`<option>${esc(x)}</option>`).join(''))}function uniq(a){return [...new Set(a)]}
function renderRows(rows){const q=norm($('#globalSearch').value),day=$('#filterDay').value,type=$('#filterType').value,mode=$('#programMode').value;let f=rows.filter(x=>{const hay=norm([x.actividad,x.titulo,x.ponente,x.detalle,x.instructor,x.lugar,x.tipo,x.fechaTexto].join(' '));return(!q||hay.includes(q))&&(!day||x.fecha===day)&&(!type||x.tipo===type)});if(mode==='talleres')f=f.filter(x=>x.kind==='taller');else if(mode==='general')f=f.filter(x=>x.kind==='programa');else if(mode==='2026-10-29'||mode==='2026-10-30')f=f.filter(x=>x.fecha===mode);const days=group(f,'fecha');$('#programContent').innerHTML=Object.entries(days).sort().map(([date,rs])=>`<section class="day-block"><h2>${esc(rs[0]?.fechaTexto||date)}</h2>${rs.sort(sortTime).map(renderProgramItem).join('')}</section>`).join('')||'<div class="empty-agenda">No se encontraron coincidencias.</div>';bindProgramButtons()}
function renderProgramItem(p){if(p.kind==='taller')return `<article class="program-block workshop"><div class="block-head"><div><span class="folio">Taller</span><h3>${esc(p.titulo)}</h3><p>${esc(p.horario)} · ${esc(p.lugar)}</p><p><b>${esc(p.instructor)}</b> · Cupo: ${esc(p.cupo)}</p></div><a class="btn primary" target="_blank" rel="noopener" href="${escAttr(p.registroUrl)}">Registrarme al taller</a></div><div class="actions"><button data-agenda="${escAttr(p.id)}">Mi Agenda</button><button data-detail="${escAttr(p.id)}">Ver detalles</button></div></article>`;return `<article class="program-block"><div class="block-head"><div><span class="folio">${esc(p.tipo)}</span><h3>${esc(p.actividad)}</h3><p>${esc(p.horario)}</p>${p.ponente?`<p><b>${esc(p.ponente)}</b>${p.detalle?`<br>${esc(p.detalle)}`:''}</p>`:''}</div><div class="actions"><button data-agenda="${escAttr(p.id)}">Mi Agenda</button><button data-detail="${escAttr(p.id)}">Ver detalles</button></div></div></article>`}
function bindProgramButtons(){$$('[data-agenda]').forEach(b=>b.onclick=()=>toggleAgenda(b.dataset.agenda));$$('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail))}
function getAgenda(){try{return JSON.parse(localStorage.getItem(agendaKey)||'[]')}catch{return[]}}function toggleAgenda(id){let a=getAgenda();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem(agendaKey,JSON.stringify(a));renderAgenda()}
function renderAgenda(){const ids=getAgenda(),rows=allItems().filter(x=>ids.includes(x.id)).sort((a,b)=>(a.fecha+a.horario).localeCompare(b.fecha+b.horario));$('#agendaCount').textContent=ids.length;$('#agendaContent').innerHTML=rows.length?rows.map(p=>`<article class="agenda-item"><span class="folio">${esc(p.tipo)}</span><h3>${esc(p.actividad||p.titulo)}</h3><p>${esc([p.fechaTexto,p.horario,p.lugar].filter(Boolean).join(' · '))}</p><button data-remove="${escAttr(p.id)}">Quitar de Mi Agenda</button></article>`).join(''):`<div class="empty-agenda"><b>Tu agenda está vacía.</b><p>Agrega actividades del programa o talleres para organizar tu visita.</p></div>`;$$('[data-remove]').forEach(b=>b.onclick=()=>toggleAgenda(b.dataset.remove))}
function openDetail(id){const p=allItems().find(x=>x.id===id);if(!p)return;$('#modalBody').innerHTML=`<span class="folio">${esc(p.tipo)}</span><h2>${esc(p.actividad||p.titulo)}</h2>${p.ponente?`<p><b>Ponente:</b> ${esc(p.ponente)}</p>`:''}${p.detalle?`<p>${esc(p.detalle)}</p>`:''}${p.instructor?`<p><b>Instructor/Conferencista:</b> ${esc(p.instructor)}</p>`:''}<p><b>Fecha:</b> ${esc(p.fechaTexto)}</p><p><b>Horario:</b> ${esc(p.horario)}</p>${p.lugar?`<p><b>Lugar:</b> ${esc(p.lugar)}</p>`:''}${p.cupo?`<p><b>Cupo:</b> ${esc(p.cupo)}</p>`:''}${p.registroUrl?`<a class="btn primary" target="_blank" rel="noopener" href="${escAttr(p.registroUrl)}">Registrarme al taller</a>`:''}`;$('#detailModal').showModal()}
function sortTime(a,b){return (a.horario||'').localeCompare(b.horario||'')}function group(a,k){return a.reduce((o,x)=>((o[x[k]||'Sin especificar']??=[]).push(x),o),{})}function norm(s){return(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function escAttr(s){return esc(s)}
init().catch(e=>{console.error(e);document.body.insertAdjacentHTML('afterbegin','<div style="padding:12px;background:#fee">No fue posible cargar los datos del evento.</div>')});
