let DATA; const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const agendaKey='cea2026_agenda';
async function init(){DATA=await fetch('data/evento.json').then(r=>r.json()); bindStatic(); renderInicio(); renderProgram(); renderAgenda(); bindNav(); tick(); setInterval(tick,60000)}
function bindStatic(){const e=DATA.evento,r=DATA.recursos; $('#heroImg').src=r.hero; $('#summaryImg').src=r.resumenVisual; $('#objective').textContent=e.objetivo; $('#audience').textContent=e.dirigidoA; $('#address').textContent=e.direccion; ['registerTop','registerMid','registerBottom'].forEach(id=>$('#'+id).href=e.registroUrl); ['callTop','callBottom'].forEach(id=>$('#'+id).href=r.convocatoriaPdf); $('#emailLink').href='mailto:'+e.contacto; $('#emailLink').textContent=e.contacto}
function renderInicio(){ $('#modalidades').innerHTML=DATA.modalidadesParticipacion.map((m,i)=>`<article class="mode"><span class="num">0${i+1}</span><h3>${esc(m.nombre)}</h3><p>${esc(m.descripcion)}</p><small>${esc(m.maxParticipantes)}</small></article>`).join(''); $('#tematicas').innerHTML=DATA.tematicas.map(t=>`<div class="theme">${esc(t)}</div>`).join('') }
function tick(){const end=new Date(DATA.evento.registroCierre),now=new Date(),d=end-now; const el=$('#countdown'); if(d<=0){el.textContent='Recepción cerrada'; return} const days=Math.floor(d/86400000),hrs=Math.floor((d%86400000)/3600000); el.textContent=`${days} días · ${hrs} h restantes`}
function bindNav(){ $$('#mainNav a').forEach(a=>a.addEventListener('click',()=>showView(a.dataset.view))); $('#menuBtn').onclick=()=>{const n=$('#mainNav');n.classList.toggle('open');$('#menuBtn').setAttribute('aria-expanded',n.classList.contains('open'))}; window.addEventListener('hashchange',()=>showView(location.hash.slice(1)||'inicio')); showView(location.hash.slice(1)||'inicio') }
function showView(id){ if(!['inicio','programa','agenda','constancias'].includes(id))id='inicio'; $$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id)); $$('#mainNav a').forEach(a=>a.classList.toggle('active',a.dataset.view===id)); $('#mainNav').classList.remove('open'); window.scrollTo(0,0); if(id==='agenda')renderAgenda() }
function renderProgram(){const rows=DATA.programa||[], c=$('#programContent'); if(!rows.length){c.innerHTML=`<div class="pending"><div class="pending-inner"><p class="eyebrow">Próximamente</p><h2>El programa general está en preparación.</h2><p>En cuanto el comité proporcione el archivo maestro, aquí aparecerá el programa completo organizado por día y mesa/bloque. No se han creado horarios, folios, autores, sedes ni actividades provisionales.</p></div></div>`;return} $('#programToolbar').hidden=false; buildFilters(rows); ['globalSearch','filterBlock','filterMod','filterType'].forEach(id=>$('#'+id).addEventListener(id==='globalSearch'?'input':'change',()=>renderRows(rows))); renderRows(rows)}
function buildFilters(rows){fill('#filterBlock',uniq(rows.map(x=>x.bloque)));fill('#filterMod',uniq(rows.map(x=>x.modalidad)));fill('#filterType',uniq(rows.map(x=>x.tipo)))} function fill(sel,arr){$(sel).insertAdjacentHTML('beforeend',arr.filter(Boolean).map(x=>`<option>${esc(x)}</option>`).join(''))} function uniq(a){return [...new Set(a)]}
function renderRows(rows){const q=norm($('#globalSearch').value),b=$('#filterBlock').value,m=$('#filterMod').value,t=$('#filterType').value; const f=rows.filter(x=>{const hay=norm([x.folio,x.titulo,(x.autores||[]).join(' '),x.bloque,x.mesa].join(' '));return(!q||hay.includes(q))&&(!b||x.bloque===b)&&(!m||x.modalidad===m)&&(!t||x.tipo===t)}); const days=group(f,'fecha'); $('#programContent').innerHTML=Object.entries(days).map(([date,rs])=>`<section class="day-block"><h2>${date}</h2>${Object.entries(group(rs,'bloque')).map(([block,items])=>renderBlock(block,items)).join('')}</section>`).join('')||'<div class="empty-agenda">No se encontraron coincidencias.</div>'; bindProgramButtons()}
function renderBlock(name,items){const x=items[0];return `<article class="program-block"><div class="block-head"><div><span class="folio">${esc(x.tipo||'')}</span><h3>${esc(name||'Bloque')}</h3><p>${esc([x.horario,x.modalidad,x.sede].filter(Boolean).join(' · '))}</p></div>${x.zoom?`<a class="btn primary" target="_blank" rel="noopener" href="${escAttr(x.zoom)}">Entrar a la sesión</a>`:''}</div>${items.map(p=>`<div class="participation"><b>${esc(p.horario||'')}</b><div><span class="folio">${esc(p.folio||'')}</span><h4>${esc(p.titulo||'')}</h4><div>${esc((p.autores||[]).join(' · '))}</div></div><div class="actions"><button data-agenda="${escAttr(p.folio)}">Mi Agenda</button><button data-detail="${escAttr(p.folio)}">Ver detalles</button></div></div>`).join('')}</article>`}
function bindProgramButtons(){ $$('[data-agenda]').forEach(b=>b.onclick=()=>toggleAgenda(b.dataset.agenda)); $$('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail)) }
function getAgenda(){try{return JSON.parse(localStorage.getItem(agendaKey)||'[]')}catch{return[]}} function toggleAgenda(id){let a=getAgenda();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem(agendaKey,JSON.stringify(a));renderAgenda()}
function renderAgenda(){const ids=getAgenda(), rows=(DATA?.programa||[]).filter(x=>ids.includes(x.folio)).sort((a,b)=>(a.fecha+a.horario).localeCompare(b.fecha+b.horario)); $('#agendaCount').textContent=ids.length; $('#agendaContent').innerHTML=rows.length?rows.map(p=>`<article class="agenda-item"><span class="folio">${esc(p.folio)}</span><h3>${esc(p.titulo)}</h3><p>${esc([p.fecha,p.horario,p.bloque,p.sede].filter(Boolean).join(' · '))}</p><button data-remove="${escAttr(p.folio)}">Quitar de Mi Agenda</button></article>`).join(''):`<div class="empty-agenda"><b>Tu agenda está vacía.</b><p>Cuando se publique el programa podrás guardar aquí las participaciones que quieras seguir.</p></div>`; $$('[data-remove]').forEach(b=>b.onclick=()=>toggleAgenda(b.dataset.remove))}
function openDetail(id){const p=DATA.programa.find(x=>x.folio===id);if(!p)return;$('#modalBody').innerHTML=`<span class="folio">${esc(p.folio)}</span><h2>${esc(p.titulo)}</h2><p><b>Autores:</b> ${esc((p.autores||[]).join(', '))}</p>${['fecha','horario','bloque','modalidad','sede'].map(k=>p[k]?`<p><b>${k[0].toUpperCase()+k.slice(1)}:</b> ${esc(p[k])}</p>`:'').join('')}${p.semblanza?`<p><b>Semblanza:</b> ${esc(p.semblanza)}</p>`:''}${p.zoom?`<a class="btn primary" target="_blank" rel="noopener" href="${escAttr(p.zoom)}">Entrar a la sesión</a>`:''}`;$('#detailModal').showModal()}
function group(a,k){return a.reduce((o,x)=>((o[x[k]||'Sin especificar']??=[]).push(x),o),{})} function norm(s){return (s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()} function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))} function escAttr(s){return esc(s)}
init().catch(e=>{console.error(e);document.body.insertAdjacentHTML('afterbegin','<div style="padding:12px;background:#fee">No fue posible cargar los datos del evento.</div>')});
